# Generated by Django 5.1.7 on 2025-03-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.IntegerField()),
                ('version', models.IntegerField()),
                ('account_id', models.CharField(max_length=50)),
                ('instance_id', models.CharField(max_length=50)),
                ('srcaddr', models.GenericIPAddressField()),
                ('dstaddr', models.GenericIPAddressField()),
                ('srcport', models.IntegerField()),
                ('dstport', models.IntegerField()),
                ('protocol', models.IntegerField()),
                ('packets', models.IntegerField()),
                ('bytes', models.BigIntegerField()),
                ('starttime', models.BigIntegerField()),
                ('endtime', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('log_status', models.CharField(max_length=10)),
            ],
        ),
    ]
