

services:
  backend:
    build: 
       context : ./backend
       dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3  # Ensures SQLite data persists
    environment:
      - DEBUG=True
    depends_on:
      - frontend
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: 
       context: ./frontend
       dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
   
